### ISSUE TITLE
Page break for multiple children

### ISSUE THREAD

**Issue by combinatorist** [code-for-nashville/power-of-attorney#118]
Fro Lori:
> PPS - I noticed when using the site if you do more than one child there isn't a good page break between the two forms.

**Comment by combinatorist** [comment]
I think this may be a good first issue for someone who knows React, but I don't know. Please let me know if it's not and I'll change the label to "help wanted".

**Comment by CoreyAR** [comment]
Because we are refactoring the form I am going to close this one and add it to the new form requirements
