### ISSUE TITLE
QA the site on mobile and file/fix responsive design issues.

### ISSUE THREAD

**Issue by CoreyAR** [code-for-nashville/power-of-attorney#26]
We need to qa the site and make sure that it is responsive across devices.

**Comment by mshenfield** [comment]
@kevinahuber has done a great first pass. We should do a second QA pass at the beginning of June.

**Comment by enlore** [comment]
Missing `Set`, `Map` polyfills. Fails to run on Win7 IE9, iPhone 5S Safari. Will edit this comment with more info.

**Comment by CoreyAR** [comment]
PR #87 closes this issue
