### ISSUE TITLE
Title Overhang

### ISSUE THREAD

**Issue by kevinahuber** [code-for-nashville/power-of-attorney#27]
Pretty minor, but the title extends past its container at 320px. Is that worth breaking grommets presets for it?
![image](https://user-images.githubusercontent.com/6272414/39611147-1120e2d8-4f1b-11e8-8d7c-1d573cf7c818.png)

**Comment by mshenfield** [comment]
If you can get it to split "immigrant" with a dash somewhere, +1

**Comment by mshenfield** [comment]
Closed by #32
