### ISSUE TITLE
Add instructions on the form download page

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/power-of-attorney#31]
We're waiting on @lgonzo1105 to provide some copy so that our landing page is more than two mysterious buttons.

<img width="1190" alt="screen shot 2018-05-03 at 11 06 45 pm" src="https://user-images.githubusercontent.com/4812055/39612623-aac61056-4f26-11e8-9bf3-57ca1e659941.png">

When she does, someone should post it here and claim this ticket to implement.

**Comment by CoreyAR** [comment]
Let's move these buttons from a separate page to beneath the form, visible after it has been submitted. This seems to be a more intuitive design and removes the need for copy.

**Comment by CoreyAR** [comment]
Instructions on how to use the form are on the first page of the app. Let's move these buttons to below the form after it has been submitted.

We will also need to remove them if any of the form data changes before it is submitted again.
