### ISSUE TITLE
Add Travis linting, testing, and deployment

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/power-of-attorney#34]
We should configure a [Node Travis setup](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) that

* lints
* tests
* builds
* and deploys to [Github Pages](https://docs.travis-ci.com/user/deployment/pages/).

**Comment by kevinahuber** [comment]
How do you feel about eslint and prettier?

**Comment by CoreyAR** [comment]
👍
