### ISSUE TITLE
Service Worker/Home Page App

### ISSUE THREAD

**Issue by kevinahuber** [code-for-nashville/power-of-attorney#35]
What is the desired outcome of an effective service worker implementation? 

On a Pixel 2 XL (Android 8.1), it works as a home screen app without connectivity (needs a title/icon), but does not within the browser.

**Comment by mshenfield** [comment]
I don't have a vision for how this should/could function offline. Maybe @coreyar can chime in.

**Comment by CoreyAR** [comment]
According to the [docs](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) the service works only work in supporting browsers in a production build and over https.

For offline homepage apps we can define a title and icon in `public/manifest.json`.

If we want to go the extra mile we can display an image to the user that the cache has populated and works offline. This can be done in `src/registerServiceWorker.js`
