### ISSUE TITLE
Hide back button on larger screens

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/power-of-attorney#43]
The "Back" button below is redundant on larger screens, where each element in the breadcrumb is clickable.  We should hide it on larger screens - although on mobile we need it because the breadcrumb is hidden.

<img width="988" alt="screen shot 2018-05-11 at 6 52 48 am" src="https://user-images.githubusercontent.com/4812055/39923120-f1a22b7e-54e7-11e8-819d-6a8297671283.png">

**Comment by coreygriggs** [comment]
pull request submitted for this
