### ISSUE TITLE
State picker bug

### ISSUE THREAD

**Issue by CoreyAR** [code-for-nashville/power-of-attorney#51]
If the page is scrolled while the state picker is open, the picker does not scroll with the rest of the page. 

http://cloud.clearsumm.it/3m1F141C3e2u

**Comment by Niicck** [comment]
https://github.com/code-for-nashville/power-of-attorney/pull/61

**Comment by CoreyAR** [comment]
Awesome. Thanks @Niicck !

**Comment by CoreyAR** [comment]
@mshenfield Thanks for merging!
