### ISSUE TITLE
Public HTML site

### ISSUE THREAD

**Issue by aaronpinch** [code-for-nashville/power-of-attorney#64]
1. http://immigrantpoa.org/ should resolve to https://github.com/code-for-nashville/power-of-attorney/blob/master/README.md (This will be only for the duration of development and testing - after completion the site will be available at this address)
2. http://immigrantpoa.org/testing/ should resolve to the _in progress_ public site under development

**Comment by CoreyAR** [comment]
Let's use a subdomain like dev or staging for the in progress site. That way all of our routes would stay the same. 

staging.immigrantpoa.org for example

**Comment by CoreyAR** [comment]
Ok the site is deployed to http://immigrantpoa.org/. I think we can create a separate ticket if we need a development environment.
