### ISSUE TITLE
Add links to relevant legal documents

### ISSUE THREAD

**Issue by combinatorist** [code-for-nashville/power-of-attorney#68]
There is a section of the form that says:
> One parent has legal custody of the minor child, and has sent by Certifed Mail, Return Receipt requested, to the other parent at last known address, a copy of this document and a notice of the provisions in § 34-6-305

So, it would make sense to provide the user with the following link so they can download, print, and actually send that form:
* TCA 34-6-305 - https://law.justia.com/codes/tennessee/2010/title-34/chapter-6/part-3/34-6-305/

Another link from Lori:
> This might be useful to link re: filling out the last question in the form re: who has custody - https://law.justia.com/codes/tennessee/2010/title-34/chapter-6/part-3/34-6-303/

We need to decide where in the experience to add these:
- As they're filling out the form?
- At the end with the open / print buttons for the form?
- Both?

**Comment by CoreyAR** [comment]
@aaronpinch I'm assigning to you so that we can follow up on Tim's questions about this ticket.

**Comment by aaronpinch** [comment]
Spoke with Lori - Link will be clickable in the UI while form is being created. Link will not included in assembled form. I will look at form with Lori and clean up description (UI is down right now)

**Comment by ntbrewer** [comment]
More recent links are available 
I recommend 
https://law.justia.com/codes/tennessee/2017/title-34/chapter-6/part-3/section-34-6-303/
https://law.justia.com/codes/tennessee/2017/title-34/chapter-6/part-3/section-34-6-305/
and 
https://www.tn.gov/tccy/publications/tennessee-code-lexis-nexis.html
The latter is for the TN Code UNannotated. but this is a real link to tn.gov and original source material is good to cite along side the more digestible link.

**Comment by CoreyAR** [comment]
@aaronpinch Can you verify and close this if it is complete?

**Comment by ntbrewer** [comment]
Talking with Lori and she suggests adding an info icon and adding the lexis nexus link.

**Comment by ntbrewer** [comment]
She also suggests adding a link on the popup after the start form button is pressed.

**Comment by aaronpinch** [comment]
Sorry for the delay - I missed the notification

I don't see the links mentioned in https://github.com/code-for-nashville/power-of-attorney/issues/68#issuecomment-410457546 

I see the changes from #86 live and working

@lgonzo1105 + @ntbrewer - Are all of the links you are requesting addressed? If not which are missing?

**Comment by CoreyAR** [comment]
In reviewing the PRs. both comments refer to the same links. If this ticket isn't finished, let's update the description with exact locations to place links and urls to be used.

**Comment by lgonzo1105** [comment]
This handles all of this.  Closing out now!  Lori G.
