### ISSUE TITLE
POA site is not accessible

### ISSUE THREAD

**Issue by aaronpinch** [code-for-nashville/power-of-attorney#72]
POA site is not accessible at http://immigrantpoa.org/

![image](https://user-images.githubusercontent.com/469503/43163501-30a1c1be-8f43-11e8-9597-6314b3302ed3.png)

**Comment by aaronpinch** [comment]
Added Corey as assignee for visibility. Please add / action as appropriate

**Comment by CoreyAR** [comment]
Fixed. We had the CNAME file in the wrong directory so deploying was causing the custom domain to be overwritten. This should be fixed going forward.
