### ISSUE TITLE
Users must acknowledge that site is in beta - click through required

### ISSUE THREAD

**Issue by aaronpinch** [code-for-nashville/power-of-attorney#73]
Problem - Users must be alerted that site is in beta BEFORE being able to browse site. This warning should not be skippable. Adding this dialogue on page load will make it easier to share POA site within legal circles during beta stage

_Formatting if possible - grey out background to highlight dialogue_ 
Draft messaging : This site is presently available as a public beta. During this time changes may occur without warning. Legal and technology professionals that wish to contribute their time and expertise can reach out to the project at https://github.com/code-for-nashville/power-of-attorney

@lgonzo1105 - Can you please review the copy above and make changes you see fit

Examples : 

![image](https://user-images.githubusercontent.com/469503/43275110-ce5655d2-90b5-11e8-873a-a6991878ec59.png)

![image](https://user-images.githubusercontent.com/469503/43274974-75632018-90b5-11e8-8d5a-161e3c178c4b.png)
https://material-ui.com/demos/dialogs/#responsive-full-screen

**Comment by aaronpinch** [comment]
@CoreyAR - please review this request - thanks

**Comment by CoreyAR** [comment]
Ideally, we wouldn't show the user two modals one right after another. If we could add information about the site being in BETA added to the disclaimer modal that would be ideal.

**Comment by lgonzo1105** [comment]
This is great as is!

Lori G.



Sent via the Samsung Galaxy S9+, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by lgonzo1105** [comment]
I have one more change to the initial modal.  Can we add the sentence by itself (perhaps right below the sentence "A copy of the Tennessee Code (T.C.A. 2017) can be found here." that says "This website does not track, keep or otherwise monitor the information inputted."  Security concerns and data tracking came up this weekend again so adding it to the initial modal might help alleviate this.  @CoreyAR

**Comment by aaronpinch** [comment]
Breaking out the above request - valid but somewhat buried here. Lori - I will tag you

**Comment by aaronpinch** [comment]
created https://github.com/code-for-nashville/power-of-attorney/issues/98 for lori's issue
