### ISSUE TITLE
Service Worker Error

### ISSUE THREAD

**Issue by CoreyAR** [code-for-nashville/power-of-attorney#74]
Completed form doesn't render a pdf because of a cross domain service worker error.

**Comment by CoreyAR** [comment]
Removing the priority label because I can't seem to reproduce this. The error is visible but I've been unable to reproduce the pdf not getting created.

**Comment by enlore** [comment]
Will take a look.

**Comment by enlore** [comment]
See section in the docs pertaining to enforcing HTTP to HTTPS redirect.

https://help.github.com/articles/securing-your-github-pages-site-with-https/ 

Seemingly resolved.
