### ISSUE TITLE
Cleanup / Appearance of Generated Form

### ISSUE THREAD

**Issue by lgonzo1105** [code-for-nashville/power-of-attorney#84]
[POA Form - Beta.pdf](https://github.com/code-for-nashville/power-of-attorney/files/2280423/POA.Form.-.Beta.pdf)
The generated form has stylistic changes to the overall format that need cleaning up so the generated form looks more like the original form.  The original form (w/ proper formatting, etc.) can be found here for reference:
URL - (https://www.tn.gov/content/dam/tn/education/legal/legal_poa_minor_child_form.pdf)

Once these changes are completed, we will be ready for onsite user testing of the project.

**Comment by lgonzo1105** [comment]
@aaronpinch @CoreyAR This is our final issue that needs addressing before we can truly begin beta testing in clinic settings.  The other issues I believe can be worked on even while beta testing.

**Comment by lgonzo1105** [comment]
[POA Form - Version 1 w revisions.pdf](https://github.com/code-for-nashville/power-of-attorney/files/2352861/POA.Form.-.Version.1.w.revisions.pdf)
 This is the form I downloaded today w/ highlights and specific notes on formatting changes.  It is best to view this and the original form (in link above) when making changes to fully understand the formatting changes needed.

**Comment by CoreyAR** [comment]
We have started making these changes on the `enhancement/84/cleanup-generated-form-appearence` branch.

**Comment by lgonzo1105** [comment]
Awesome - I am not sure I know how to read that part :)  Let me know what I can do next!

**Comment by CoreyAR** [comment]
@lgonzo1105 The form has been updated.

**Comment by lgonzo1105** [comment]
These changes are great and I will start beta testing w/ this form very soon at actual clinics.  Closing this issue for now.
