### ISSUE TITLE
Make default behavior if field is a empty/whitespace character. 

### ISSUE THREAD

**Issue by ntbrewer** [code-for-nashville/power-of-attorney#85]
Lori and I were discussing being able to have a default behavior which would allow for a user to generate a long blank to be filled in by hand after generation of the form. 

Right now the form validates white space. Can we turn this into a default behavior?

We could also have blank default behavior in the final form with a notification. 

A choice should be made.

**Comment by CoreyAR** [comment]
Should the user be able to generate a partially complete form?

I think we would want the user to completely fill out the form online or choose to print out a blank form.

**Comment by aaronpinch** [comment]
I see the following ways to approach this; other ideas welcome

1. Allow only a completed form to be printed; requiring users that want a blank one to print it from a link we can provide (IE - do nothing)
2. Allow partial forms + require confirmation that the user wants to "skip" a field (IE - leave it blank with a white space). This will probably require a user to click on each field they want blank
3. Allow partial forms + require user to add a tag to leave a white space (EG "blank")
4. Allow partial forms + accept a blank entry as valid. Any blanks would be replaced with white space on form generation

My 2 cents - of the options to add this functionality #2 is the most cumbersome for both the app/development team + the user. #4 is probably the easiest to implement, but also easy for a user to leave a blank in error. 

Options 2-4 need a notation on the cover page that states that blanks need to be addressed or the form might be invalid

How often is a partially filled form needed? Is this anticipated to be a frequent problem, or are we looking at an edge case?

Looking for input from @lgonzo1105 + @ntbrewer

**Comment by CoreyAR** [comment]
We can implement 1 the easiest. 2 - 4 degrade the quality of the form validation. They will result in a form with some typed and some handwritten entries which may not be acceptable.

**Comment by lgonzo1105** [comment]
I believe we need the option of having partially blank fields throughout the field.  There may be times when a parent or caregiver's address may not be known at the time of filling this form out.  The ultimate goal of the form was to minimize some of the handwriting necessary to get the forms complete.  The reality of the forms and the info that is available when filling out the forms, is that there will always be items that need to be signed, updated or perhaps even filled out after the form is physically generated.  So, in a perfect world, there will be blank lines and the option to leave those sections blank if the info is not readily available.  Let me know if that helps!

**Comment by CoreyAR** [comment]
#94  closes this. Waiting fo review.

**Comment by CoreyAR** [comment]
We may want to require all address fields or no address fields. If state and zipcode are filled out but not city the formatting doesn't leave room for the city.

**Comment by lgonzo1105** [comment]
I like that idea Corey.  If they do not have a complete address (except perhaps the zip code), we don't allow them to fill it out?  Also, can you remove the comma after the state initials in the form?  Should just be a comma after the city, not the state.

**Comment by CoreyAR** [comment]
I pushed up a fix for the command after the state. I made a separate ticket for changing how the address is validated. 

Otherwise, this can be closed if it passes QA.

**Comment by aaronpinch** [comment]
A minor request @CoreyAR - we can resolve it here or I can write up a new request - let me know your preference: 

- Can we omit the state name if the address is blank (Possible solutions - 1) if address is blank than state treated as blank 2) Don't autoselect TN on forms. Rather put it at the top of the dropdown

![image](https://user-images.githubusercontent.com/469503/45372051-d94e9200-b5a0-11e8-93d6-2241fee65418.png)

**Comment by aaronpinch** [comment]
Found https://github.com/code-for-nashville/power-of-attorney/issues/97 - moving the above item and closing this request
