### ISSUE TITLE
Translate the application into Spanish

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/power-of-attorney#9]
At some point we need to translate the text of this into Spanish, and use a React translation utility to put in the right text depending on the client's language settings.

**Comment by CoreyAR** [comment]
The first step for this will be to pull out all the strings into a separate file.

**Comment by mshenfield** [comment]
English strings have been pulled into [src/strings/english.js](src/strings/english.js) in #23.  The next step is to use https://github.com/i18next/react-i18next to use these strings in the app.

**Comment by CoreyAR** [comment]
@jjsub Do you have an update on where we are at with translations?

**Comment by ntbrewer** [comment]
Working on this.

**Comment by aaronpinch** [comment]
Related pull request : #https://github.com/code-for-nashville/power-of-attorney/pull/70

**Comment by CoreyAR** [comment]
This ticket has been completed. We still need to add some UI to toggle between languages and possibly some logic to detect the user's language. 

We can make a separate ticket for that.
