### ISSUE TITLE
Improve Dropdown Component

### ISSUE THREAD

**Issue by aaronpinch** [code-for-nashville/power-of-attorney#90]
Problem : Users of POA app need to manually select their state, despite that the intended jurisdiction is Tennessee. Further the existing select is not searchable by text meaning that the user must scroll to the bottom of the list

Solution : We would like to see the list simplified. The main objective is to place Tennessee at top of the list as currently the forms are only designed for this jurisdiction

We would like to suggest that Tennessee is autofilled but a user can override the selection by typing in another state (see example below). If this is too complex to implement then simply moving Tennessee to the top of the list will suffice

Existing UI : 

![image](https://user-images.githubusercontent.com/469503/44358935-4459ec80-a46b-11e8-81fd-f25620a0a63c.png)

Considerations : 
- keep full names (please do not abbreviations)
- auto fill tennessee, but allow the user to override the selection
- the main objective is to make Tennessee easy to select

Example : https://material-ui.com/demos/autocomplete/

**Comment by CoreyAR** [comment]
@aaronpinch The select component update has been merged. Ready for QA.

**Comment by aaronpinch** [comment]
Looks great @CoreyAR - no concerns or problems found. Closing

FYI @lgonzo1105
