### ISSUE TITLE
Add privacy notice to disclaimer page - (https://immigrantpoa.org/#/form)

### ISSUE THREAD

**Issue by aaronpinch** [code-for-nashville/power-of-attorney#98]
Per @lgonzo1105  : 

Can we bold the sentence "This site does not track, save, or retain any information entered." to ease concerns re: data tracking on the initial warning?

![2018-09-11_09h09_37](https://user-images.githubusercontent.com/469503/45372686-73fba080-b5a2-11e8-9de4-179f17f516ef.png)

attention : @CoreyAR

**Comment by aaronpinch** [comment]
@lgonzo1105 - please post if you want to see any changes from the above

**Comment by lgonzo1105** [comment]
@aaronpinch I updated the request to just request a bolding of the sentence we already had.  Thanks for catching that!!

**Comment by cdaniel3** [comment]
The privacy notice doesn't appear on the Spanish version of the disclaimer.  In fact, this section is missing from the Spanish version:

> This form is legal information, not legal advice. While this form in no way terminates your rights as a parent, it does provide a caregiver authority to care for your child(ren). If you are unsure of your rights or needs, you should consult an attorney to discuss your legal needs. This site does not track, save, or retain any information entered. 

Should I create another issue to track adding this text?

**Comment by combinatorist** [comment]
@aaronpinch, what do you think about providing or securing an endorsement from a third-party that data does not leave the client-device or go to any server? I think emphasizing the fact that it's private is good, but some users might not want to take our word for it. @lgonzo1105 thought you or one of your organizations might be willing to certify the site's privacy. What do you think?

**Comment by bitcode** [comment]
finished translation, "Add privacy notice to disclaimer page" and pushed changes

**Comment by CoreyAR** [comment]
Closing because @combinatorist  merged PR #117
